
CREATE TABLE client (
    id_client  NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nom_client VARCHAR2(100) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE item (
    id_item            NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    qté                NUMBER(3) NOT NULL,
    produit_id_produit NUMBER(5) NOT NULL,
    panier_id_client   NUMBER(5) NOT NULL,
    id_produit         NUMBER(5) NOT NULL
);

ALTER TABLE item ADD CONSTRAINT item_pk PRIMARY KEY ( id_item );

CREATE SEQUENCE panier_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE TABLE panier (
    client_id_client NUMBER(5) NOT NULL,
    id_client        NUMBER(5) DEFAULT panier_id_client_seq.NEXTVAL NOT NULL,
    id_item          NUMBER(5) NOT NULL
);

CREATE UNIQUE INDEX panier__idx ON
    panier (
        client_id_client
    ASC );

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_client );

CREATE TABLE produit (
    id_produit  NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nom_produit VARCHAR2(150) NOT NULL,
    prix        NUMBER(5) NOT NULL,
    description VARCHAR2(1000) NOT NULL,
    stock       NUMBER(5) NOT NULL,
    categorie   VARCHAR2(50) NOT NULL,
    langue      VARCHAR2(3) NOT NULL
);

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

ALTER TABLE item
    ADD CONSTRAINT item_panier_fk FOREIGN KEY ( panier_id_client )
        REFERENCES panier ( id_client );

ALTER TABLE item
    ADD CONSTRAINT item_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE panier
    ADD CONSTRAINT panier_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );