CREATE TABLE client (
    id_client  NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nom_client VARCHAR2(100) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE item (
    id_item            NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    qte                NUMBER(3) NOT NULL,
    produit_id_produit NUMBER(5) NOT NULL,
    panier_id_panier   NUMBER(5) NOT NULL
);

ALTER TABLE item ADD CONSTRAINT item_pk PRIMARY KEY ( id_item );

CREATE TABLE panier (
    client_id_client NUMBER(5) NOT NULL,
    id_item          NUMBER(5) NOT NULL,
    id_panier        NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL
);

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_panier );

CREATE TABLE produit (
    id_produit      NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    nom_produit     VARCHAR2(150) NOT NULL,
    prix            NUMBER(5) NOT NULL,
    description     VARCHAR2(1000) NOT NULL,
    stock           NUMBER(5) NOT NULL,
    categorie       VARCHAR2(50) NOT NULL,
    langue          VARCHAR2(3) NOT NULL,
    auteur          VARCHAR2(100) NOT NULL,
    genre           VARCHAR2(5) NOT NULL,
    datepublication DATE NOT NULL,
    image           VARCHAR2(100) NOT NULL
);

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

ALTER TABLE item
    ADD CONSTRAINT item_panier_fk FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );

ALTER TABLE item
    ADD CONSTRAINT item_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE panier
    ADD CONSTRAINT panier_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

Insert into CLIENT (ID_CLIENT,NOM_CLIENT) values (89521,'Michel Terrier');
commit;

Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (1,'Red Rising',21,'Darrow is a Red, a member of the lowest caste in the color-coded society of the future. Like his fellow Reds, he works all day, believing that he and his people are making the surface of Mars livable for future generations. Yet he toils willingly, trusting that his blood and sweat will one day result in a better world for his children.

But Darrow and his kind have been betrayed. Soon he discovers that humanity reached the surface generations ago. Vast cities and lush wilds spread across the planet. Darrow—and Reds like him—are nothing more than slaves to a decadent ruling class.',1,'Ado','En','Pierce Brown','Dyst',to_date('15-JUL-14','DD-MON-RR'),'../images/redrising.webp');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (2,'Hunger Games Box Set',56,'Winning means fame and fortune.

Losing means certain death.',1,'Ado','En','Suzanne Collins','Dyst',to_date('04-FEB-25','DD-MON-RR'),'../images/hungergames.avif');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (3,'Smile',17,'Raina just wants to be a normal sixth grader. But one night after Girl Scouts she trips and falls, severely injuring her two front teeth. What follows is a long and frustrating journey with on-again, off-again braces, surgery, embarrassing headgear, and even a retainer with fake teeth attached. And on top of all that, there''s still more to deal with: a major earthquake, boy confusion, and friends who turn out to be not so friendly.',0,'Enf','En','Raina Telgemeier','Romc',to_date('10-NOV-20','DD-MON-RR'),'../images/smile.jpg');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (4,'It Ends With Us',17,'Lily hasn’t always had it easy, but that’s never stopped her from working hard for the life she wants. She’s come a long way from the small town where she grew up—she graduated from college, moved to Boston, and started her own business. And when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily’s life seems too good to be true.

As questions about her new relationship overwhelm her, so do thoughts of Atlas Corrigan—her first love and a link to the past she left behind. He was her kindred spirit, her protector. When Atlas suddenly reappears, everything Lily has built with Ryle is threatened.',1,'Adu','En','Colleen Hoover','Romc',to_date('02-AUG-16','DD-MON-RR'),'../images/itendswithus.jpg');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (5,'Amos Daragon 1',6,'Amos Daragon, un brillant garçon de douze ans, devient malgré lui le premier élu de la nouvelles génération des porteurs de masques. Instauré par la Dame Blanche, déesse suprême, ce culte modifiera sa destinée et celle de ses parents. Sa dangeureuse mission consiste à rétablir l''équilibre du monde, menacé par la guerre sans merci que se livrent les dieux du bien et du mal. Grâce à ses pouvoirs sur les éléments et aidé de Béorf Bromanson, un jeune garçon de la race des béorites capable de se transformer en ours, Amos parcourt des contrées étranges peuplées de créatures légendaires, à la recherche des masques de pouvoir. Cette épopée mythologique est un plongeon tête première dans la fantaisie, la magie et l''imagination.',1,'Enf','Fr','Bryan Perro','Fant',to_date('19-MAR-23','DD-MON-RR'),'../images/amosdaragon.jpg');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (6,'Warrior Cats Box Set',67,'For generations, four Clans of wild cats have shared the forest according to the laws laid down by their warrior ancestors. But now ThunderClan is in grave danger. Rival ShadowClan is growing stronger, a traitor may be hiding in their midst, and rising tensions threaten every cat in the forest.

In the dark days ahead, ThunderClan’s fate will rest in the paws of an unexpected hero: an ordinary house cat named Rusty…who may yet turn out to be the bravest warrior of them all.',0,'Enf','En','Erin Hunter','Fant',to_date('17-MAR-15','DD-MON-RR'),'../images/warriorcats.jpg');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (7,'Les Piliers de la Terre',38,'1123. Motivés par d''obscures raisons, un prêtre, un chevalier et un moine font pendre un prisonnier après un procès expéditif.

Une étrange malédiction semble alors s''abattre sur eux.

Dans un royaume d''Angleterre en perdition, morcelé par la guerre, affaibli par la famine et une épouvantable crise religieuse, noblesse et clergé rivalisent d''inventivité pour s''approprier le pouvoir. Lorsque le projet de construction d''une grande cathédrale est annoncé, chacun y voit l''occasion de servir ses propres intérêts...

Les destins de Philip, le prieur, de Jack, le bâtisseur, ou de la jeune aristocrate Aliena vont s''entremêler. Tous égaux devant Dieu, ils seront seuls pour affronter leur sort.',1,'Adu','Fr','Ken Follett','Class',to_date('11-SEP-17','DD-MON-RR'),'../images/lespiliersdelaterre.jpg');
Insert into PRODUIT (ID_PRODUIT,NOM_PRODUIT,PRIX,DESCRIPTION,STOCK,CATEGORIE,LANGUE,AUTEUR,GENRE,DATEPUBLICATION,IMAGE) values (8,'Le Comte de Monte Cristo I',27,'Découvrez le début captivant de Le Comte de Monte-Cristo, l’un des chefs-d''œuvre les plus marquants d''Alexandre Dumas, publié pour la première fois en 1846. Ce classique intemporel nous plonge dans la vie d''Edmond Dantès, jeune marin dont l''ascension est brutalement stoppée par une trahison. Emprisonné injustement, Dantès se forge une nouvelle identité mystérieuse, celle du Comte de Monte-Cristo, et entreprend une quête de vengeance calculée. Ce premier volume vous transporte au cœur de son emprisonnement et des premières étapes de sa transformation intérieu',1,'Adu','Fr','Alexandre Dumas','Class',to_date('28-OCT-24','DD-MON-RR'),'../images/comtedemontecristo.jpg');
commit;